#!/usr/bin/env php
<?php

use App\Engine\ConcurrentEngine;
use App\Processor\Processor;
use App\Scheduler\QueueScheduler;
use App\Server\Protocol;
use App\Server\PoolServer;
use App\Server\SwooleServer;
use App\Table\Cache;
use Swoole\Table;

require __DIR__.'/bootstrap/app.php';

// Table store
$table = new Table(1<<6);
$table->column('id', Table::TYPE_INT);
$table->column('status_code', Table::TYPE_INT);
$table->column('response_body', Table::TYPE_STRING, 1024);
$table->create();

// Cache.err for manage the Table
$cache = new Cache($table);

// Spider engine
$engine = new ConcurrentEngine(
    new QueueScheduler(),
    new Processor($cache),
    100,
);

// tcp server
//$server = new PoolServer('0.0.0.0', 8080, new Protocol(), $engine);

// swoole server
$server = new SwooleServer('0.0.0.0', 8080, new Protocol(), $engine, $cache);
$server->start();